export const LOAD_CATEGORIE = "LOAD_CATEGORIE";
export const GET_CATREGORIES = "GET_CATREGORIES";
export const CURRENT_UTILISATEUR = "CURRENT_UTILISATEUR";
export const FAIL_CATEGORIE = "FAIL_CATEGORIE";