export const LOAD_UTILISATEUR = "LOAD_UTILISATEUR";
export const LOGIN_UTILISATEUR = "LOGIN_UTILISATEUR";
export const CURRENT_UTILISATEUR = "CURRENT_UTILISATEUR";
export const FAIL_UTILISATEUR = "FAIL_UTILISATEUR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
